# Generated by Django 4.1.1 on 2022-09-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='published',
            new_name='active',
        ),
    ]
