# Generated by Django 4.1.1 on 2022-09-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notion', '0002_rename_published_task_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Typing',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='typing',
        ),
    ]
