# Generated by Django 4.1.1 on 2022-10-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notion', '0003_rename_type_typing_rename_type_task_typing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
